version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_DB: productos
      POSTGRES_USER: service
      POSTGRES_PASSWORD: notapassword
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - productos-red

  producto-1:
    image: productos
    container_name: productos-nodo-1
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_HOST: postgres
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DATABASE: productos
    depends_on:
      - postgres
    networks:
      - productos-red

  producto-2:
    image: productos
    container_name: productos-nodo-2
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_HOST: postgres
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DATABASE: productos
    depends_on:
      - postgres
    networks:
      - productos-red

  producto-3:
    image: productos
    container_name: productos-nodo-3
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_HOST: postgres
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DATABASE: productos
    depends_on:
      - postgres
    networks:
      - productos-red


networks:
  productos-red:
    driver: bridge
